# Generated by Django 5.1.7 on 2025-03-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', help_text='Designates whether the user is a student or a teacher.', max_length=10),
        ),
    ]
