# Generated by Django 5.1.7 on 2025-03-07 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='room_name',
            field=models.CharField(max_length=255),
        ),
    ]
