# Generated by Django 5.1.7 on 2025-03-08 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatmessage_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='sender',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
